/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package atividadeavaliativa01;

import java.awt.Image;
import java.io.BufferedWriter;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.nio.charset.StandardCharsets;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author dijan
 */
public class JFrameNovoUsuario extends javax.swing.JFrame {

    /**
     * Creates new form JFrameGerenciarUsuarios
     */
    public static ArrayList<Cadastro> db = new ArrayList<Cadastro>();
    private int index = 0;
    private boolean novoUsuario = false;
    JFrameGerenciarUsuarios gerenciarUsuarios;

    public JFrameNovoUsuario(ArrayList<Cadastro> cadastro) {
        this.db = cadastro;
        initComponents();
        this.iniciarComponente();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelImage = new javax.swing.JLabel();
        labelNome = new javax.swing.JLabel();
        labelIdade = new javax.swing.JLabel();
        labelAltura = new javax.swing.JLabel();
        labelEstado = new javax.swing.JLabel();
        labelCidade = new javax.swing.JLabel();
        labelEndereco = new javax.swing.JLabel();
        inputNome = new javax.swing.JTextField();
        inputIdade = new javax.swing.JTextField();
        inputAltura = new javax.swing.JTextField();
        inputEstado = new javax.swing.JTextField();
        inputCidade = new javax.swing.JTextField();
        inputEndereco = new javax.swing.JTextField();
        avancar = new javax.swing.JButton();
        voltar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelImage.setBackground(new java.awt.Color(123, 123, 123));
        labelImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelImage.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.lightGray, java.awt.Color.white));
        labelImage.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        labelNome.setText("Nome:");

        labelIdade.setText("Data de nascimento:");

        labelAltura.setText("Altura:");

        labelEstado.setText("Estado:");

        labelCidade.setText("Cidade:");

        labelEndereco.setText("Endereço:");

        inputNome.setBorder(null);
        inputNome.setMaximumSize(new java.awt.Dimension(20, 14));
        inputNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNomeActionPerformed(evt);
            }
        });

        inputIdade.setBorder(null);
        inputIdade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputIdadeActionPerformed(evt);
            }
        });

        inputAltura.setBorder(null);

        inputEstado.setBorder(null);

        inputCidade.setBorder(null);

        inputEndereco.setBorder(null);
        inputEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputEnderecoActionPerformed(evt);
            }
        });

        avancar.setText("Criar");
        avancar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                avancarActionPerformed(evt);
            }
        });

        voltar.setText("Cancelar");

        jButton1.setText("Limpar formulario");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(voltar))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(labelIdade)
                                        .addGap(15, 15, 15)
                                        .addComponent(inputIdade))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(labelEndereco)
                                        .addGap(15, 15, 15)
                                        .addComponent(inputEndereco))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(labelAltura)
                                            .addComponent(labelEstado)
                                            .addComponent(labelCidade))
                                        .addGap(11, 11, 11)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(inputCidade)
                                            .addComponent(inputEstado)
                                            .addComponent(inputAltura)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(labelNome)
                                        .addGap(18, 18, 18)
                                        .addComponent(inputNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                        .addGap(18, 18, 18)
                        .addComponent(avancar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelImage, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 464, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelImage, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNome)
                    .addComponent(inputNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelIdade)
                    .addComponent(inputIdade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelAltura)
                    .addComponent(inputAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelEstado)
                    .addComponent(inputEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCidade)
                    .addComponent(inputCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEndereco)
                    .addComponent(inputEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(avancar)
                    .addComponent(voltar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNomeActionPerformed
        // TODO add your handling code here:
//        System.out.println("Boaa " + cadastro.get(0).getNome());
//        this.inputNome.setText(cadastro.get(0).getNome());
    }//GEN-LAST:event_inputNomeActionPerformed

    private void inputIdadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputIdadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputIdadeActionPerformed

    private void inputEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputEnderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputEnderecoActionPerformed

    private void avancarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_avancarActionPerformed
        // TODO add your handling code here:
        System.out.println("vamos salvar");
//        this.inputNome.getText();
//        this.inputIdade.getText();
//        this.inputAltura.getText();
//        this.inputEstado.getText();
//        this.inputCidade.getText();
//        this.inputEndereco.getText();
//        this.labelImage.getText();
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        Date data;
        try {
            data = formato.parse("23/11/1995");

            Estado estado = new Estado("SP", "São Paulo");
//        Cadastro y = new Cadastro("Any Nome", "Any Endereço", estado, "Any Cidade", data, (float) 1.70, 321, imagem);

            Cadastro cd = new Cadastro(
                    this.inputNome.getText(),
                    this.inputEndereco.getText(),
                    estado,
                    this.inputCidade.getText(),
                    data,
                    Float.parseFloat(this.inputAltura.getText()),
                    355,
                    new ImageIcon("default.jpg")
            );
            this.db.add(cd);
        } catch (ParseException ex) {
            Logger.getLogger(JFrameNovoUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            this.escrever_arquivo();
//            changeFormItems();
        } catch (IOException ex) {
            Logger.getLogger(JFrameNovoUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_avancarActionPerformed

    private void limparComponente() {
        this.inputNome.setText("");
        this.inputIdade.setText("");
        this.inputAltura.setText("");
        this.inputEstado.setText("");
        this.inputCidade.setText("");
        this.inputEndereco.setText("");
        this.labelImage.setIcon(lidarComImagem(new ImageIcon("default.jpg")));
    }

    private void iniciarComponente() {
        this.labelImage.setIcon(lidarComImagem(new ImageIcon("default.jpg")));
    }

    private ImageIcon lidarComImagem(ImageIcon imagem) {
        ImageIcon imageIcon = imagem;
        Image image = imageIcon.getImage();
        Image newimg = image.getScaledInstance(114, 114, java.awt.Image.SCALE_SMOOTH);

        return new ImageIcon(newimg);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameNovoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameNovoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameNovoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameNovoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameNovoUsuario(db).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton avancar;
    private javax.swing.JTextField inputAltura;
    private javax.swing.JTextField inputCidade;
    private javax.swing.JTextField inputEndereco;
    private javax.swing.JTextField inputEstado;
    private javax.swing.JTextField inputIdade;
    private javax.swing.JTextField inputNome;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel labelAltura;
    private javax.swing.JLabel labelCidade;
    private javax.swing.JLabel labelEndereco;
    private javax.swing.JLabel labelEstado;
    private javax.swing.JLabel labelIdade;
    private javax.swing.JLabel labelImage;
    private javax.swing.JLabel labelNome;
    private javax.swing.JButton voltar;
    // End of variables declaration//GEN-END:variables

    void setGerenciarUsuarios(JFrameGerenciarUsuarios gerenciarUsuarios) {
        this.gerenciarUsuarios = gerenciarUsuarios;
    }

    public void escrever_arquivo() throws IOException {

//        BufferedWriter buffWrite = new BufferedWriter(new FileWriter("bd.txt", StandardCharsets.ISO_8859_1, false));

        try {
            FileOutputStream writeData = new FileOutputStream("bd.txt");
            
            ObjectOutputStream writeStream = new ObjectOutputStream(writeData);

            writeStream.writeObject(db);
            writeStream.flush();
            writeStream.close();

        } catch (IOException e) {
            e.printStackTrace();
        }
        
//        
//        for (int i = 0; i < db.size(); i++) {
//            System.out.println("test " + db.get(i).toString());
////            buffWrite.append(db.get(i) + "\n");
//        }
//
//        buffWrite.close();
    }
}
